sudo: false
language: node_js
node_js: stable
cache:
  directories:
    - $HOME/.npm
stages:
  - lint
  - test
  - greenkeeper
jobs:
  include:
    - stage: lint
      script: npm run lint:js
      name: "Lint JS"
    - script: npm run lint:docker
      name: "Lint Dockerfile"
    - script: npm run lint:ec
      name: "Lint for editorconfig"
    - stage: test
      script: npm run test:js
      after_success: npm run coverage
    - stage: greenkeeper
      if: branch =~ /^greenkeeper.*$/ # only run if in a greenkeeper branch
      before_install: npm i -g greenkeeper-lockfile
      install: npm i # always run full install for greenkeeper
      script:
        - greenkeeper-lockfile-update
        - greenkeeper-lockfile-upload
